// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBLei6ssOwPMonT0gvYe0524SbGsdz5io',
    appId: '1:399851150525:web:2370cd359efb1dc72c6bd4',
    messagingSenderId: '399851150525',
    projectId: 'gondaliyafamily-d7002',
    authDomain: 'gondaliyafamily-d7002.firebaseapp.com',
    storageBucket: 'gondaliyafamily-d7002.firebasestorage.app',
    measurementId: 'G-KDXJM6KCFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjifqpeFWpfXxG_0gRMLaA5jHZCnlOl_U',
    appId: '1:399851150525:android:5d92a40522c4deff2c6bd4',
    messagingSenderId: '399851150525',
    projectId: 'gondaliyafamily-d7002',
    storageBucket: 'gondaliyafamily-d7002.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkeQPPJHOp6-6O4KsXNRTjvuzJ95valuc',
    appId: '1:399851150525:ios:660cc92c2d4831f62c6bd4',
    messagingSenderId: '399851150525',
    projectId: 'gondaliyafamily-d7002',
    storageBucket: 'gondaliyafamily-d7002.firebasestorage.app',
    iosBundleId: 'com.example.gondaliaFamily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkeQPPJHOp6-6O4KsXNRTjvuzJ95valuc',
    appId: '1:399851150525:ios:660cc92c2d4831f62c6bd4',
    messagingSenderId: '399851150525',
    projectId: 'gondaliyafamily-d7002',
    storageBucket: 'gondaliyafamily-d7002.firebasestorage.app',
    iosBundleId: 'com.example.gondaliaFamily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBLei6ssOwPMonT0gvYe0524SbGsdz5io',
    appId: '1:399851150525:web:5c17e64115d94cd62c6bd4',
    messagingSenderId: '399851150525',
    projectId: 'gondaliyafamily-d7002',
    authDomain: 'gondaliyafamily-d7002.firebaseapp.com',
    storageBucket: 'gondaliyafamily-d7002.firebasestorage.app',
    measurementId: 'G-HV1PGCB72F',
  );
}
